version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.7

workflows:
  testing:
    jobs:
      - Maven-Build
      - docker-publish/publish:
          registry: https://hub.docker.com/
          dockerfile: ~/Dockerfile
jobs:
  Maven-Build:
    docker:
      - image: maven:3.8.6-openjdk-11
    resource_class: hardik2607/circle-ci
    steps:
      - checkout
      - restore_cache:
          key: maven-cache
      - run:
          command: |
            mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache 
      - docker-publish
