version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    docker:
      - image: ubuntu:latest
    resource_class: hardik2607/circle-ci
    steps:
      - run: echo "Hi I'm on Runners!"
