version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.7

workflows:
  testing:
    jobs:
      - Maven-Build
      - Docker-Build

jobs:
  Maven-Build:
    docker:
      - image: maven:3.8.6-openjdk-11
    resource_class: hardik2607/circle-ci
    steps:
      - checkout
      - restore_cache:
          key: maven-cache
      - run:
          command: |
            mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache 
  Docker-Build:
    docker:
      - image: node:14
    resource_class: hardik2607/circle-ci
    steps:
      - docker-publish:
          deploy: false
          image: $CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM