version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  maven: circleci/maven@1.1
workflows:
  testing:
    jobs:
      - Maven-Build:
          name: Maven-Build
          app_folder: .
          path: .
          dockerfile: Dockerfile
          tags: $CIRCLE_BUILD_NUM
      # - check-and-build-only:
      #     requires:
      #       - "Maven-Build"
jobs:
  Maven-Build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk #maven:3.8.6-openjdk-11
    resource_class: hardik2607/circle-ci
    # parametes:
    #     dockerfile: 
    #       type: string
    #     image: 
    #       type: 
    #         string
    #     path: 
    #       type: string 
    #     tag: 
    #       type: string
    #     extra_build_ags:
    #       type: string
    #     use-buildkit: 
    #       type: boolean
    steps:
      - checkout
      - restore_cache:
          key: maven-cache
      - run:
          command: |
            mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache
      - run: 
          command: |
            echo "DOCKER BUILD"
      - docker/build:
          dockerfile: Dockerfile
          image: $CIRCLE_PROJECT_REPONAME
          path: . 
          tag: $CIRCLE_BUILD_NUM
          use-buildkit: true
          # extra_build_ags: <<parameters.extra_build_args>>