version: 2.1
orbs:
  docker: circleci/docker@2.1.4
  maven: circleci/maven@1.1
workflows:
  testing:
    jobs:
      - Maven-Build
      - build:
          requires:
            - Maven-Build
jobs:
  Maven-Build:
    docker:
      - image: maven:3.8.6-openjdk-11
    resource_class: hardik2607/circle-ci
    steps:
      - checkout
      - run:
          command: |
            uname -a
            mvn clean install
            ls -l
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: docker:latest
    resource_class: hardik2607/circle-ci
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            docker build . 
